name: candidate
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  auth: 
    path: ../../packages/auth/
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^2.1.3
  go_router: ^6.0.6
  intl: ^0.17.0
  riverpod_annotation: ^1.1.1
  theme:
    path: ../../packages/theme/
  utils:
    path: ../../packages/utils/

dev_dependencies:
  build_runner: ^2.3.3
  build_verify: ^3.1.0
  flutter_test:
    sdk: flutter
  go_router_builder: ^1.1.0
  mocktail: ^0.3.0
  riverpod_generator: ^1.1.1
  very_good_analysis: ^4.0.0

flutter:
  uses-material-design: true
  generate: true
