name: auth
description: “Auth”
version: 0.1.0+1
publish_to: none

environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.1.3
  freezed_annotation: ^2.2.0
  riverpod_annotation: ^1.1.1
  shared_preferences: ^2.0.17
  utils:
    path: ../utils/

dev_dependencies:
  build_runner: ^2.3.3
  flutter_gen_runner: ^5.2.0
  flutter_test:
    sdk: flutter
  freezed: ^2.3.2
  mocktail: ^0.3.0
  riverpod_generator: ^1.1.1
  very_good_analysis: ^4.0.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/

flutter_gen:
  assets:
    outputs:
      package_parameter_enabled: true